### ISSUE TITLE
Show percentage 

### ISSUE THREAD

**Issue by 24seconds** [24seconds/rust-cli-pomodoro#126]
While using the app, I found that sometimes I need to finish pomodoro timer early. In that case, I want to record how much did I spend - 70%, 50% for example. Let's make this option

This is adding new column named percentage

**Comment by 24seconds** [comment]
Maybe adding flag to `ls` would be fine. For example, `ls -p` would show the table with percentage columns.

#### The percentage calculation
Let say 1 pomodoro is consisted of 25 minutes work and 5 minutes break. But during the percentage calculation, break is not considered.  
For example, If the time passed 10 minutes from I started the timer then the percentage should be (10/25 * 100 = 40%).
If the time passed more than 25 minutes (that means it's in the break time), then the percentage should be 100%, because work time has gone.

**Comment by TheRustyPickle** [comment]
I would like to work on this if it's available.

**Comment by 24seconds** [comment]
Hello @TheRustyPickle ! Thank you for making PR and leaving comment here. Yesterday, I gave this issue to other person (#140). So.. how about this issues ? (#63 or #52). If you choose one of them, I will give you a detail guide if you need. Thank you again!

@docongminh

**Comment by TheRustyPickle** [comment]
I can try working on #63. If you have any guide or tips, it would be quite helpful as well. Thank you, @24seconds!

**Comment by 24seconds** [comment]
@TheRustyPickle Ooops sorry. I missed this. I will write some guide soon.

**Comment by 24seconds** [comment]
[Update]
For anyone who is interested in this issue, please feel free to work on.

**Comment by TheRustyPickle** [comment]
Hello @24seconds, I can work on this issue but I need suggestions on how to proceed. It seems the `Tabled` trait is implemented for the `Notification` struct, how would you recommend I should proceed to add the extra column when the `-p` flag is passed?

**Comment by 24seconds** [comment]
Hello @TheRustyPickle , thank you for being interested in this issue!
Yes, I also looked up the code and I think we can do this with latest `tabled` package version (v0.10.0)

There are two options. Take a look tabled [README.md](https://github.com/zhiburt/tabled/blob/837bed213e824ced96cd7e9dc18a0c8c439fc314/README.md?plain=1#L1)
To do this, we should upgrade the version of `tabled` package.

### Option1: use Disabled
Modify the `impl Tabled for Notification` part. Length should be 8. New column named `percentage`. Value should be `0%` to `100%`.

If the `list` is given, Disable the last column (`percentage`). If the `list -p` is given, then do not disable.

### Option2: use Merge
Do not modify notification.
When handling the `list -p`, create another table based on notification. The table has only one column named `percentage` and the values are `0%` to `100%`.
Merge current table and new table.

I think both are fine. What do yo think?

**Comment by 24seconds** [comment]
If you agree than I guess it would be nice to separate PRs
- one for upgrading `tabled` version
- the other one for implementing `show percentage` feature

**Comment by TheRustyPickle** [comment]
Thank you so much! I haven't finished reading Tabled docs or readme yet. Sorry if the question came out as naive😅

Perhaps this one would be easier as the trait implementation function already has the data readily available?
>Option1: use Disabled

Of course. Will work on upgrading the `tabled` version.
>If you agree than I guess it would be nice to separate PRs

**Comment by 24seconds** [comment]
It's up to you @TheRustyPickle . Option1 or Option2 are totally fine. Or any suggestions are welcome.

> Of course. Will work on upgrading the tabled version.

Thank you!
