### ISSUE TITLE
print message with timestamp

### ISSUE THREAD

**Issue by 24seconds** [24seconds/rust-cli-pomodoro#135]
sometimes I want to check when did I run the command without typing the command. 

This is current stdout message.
As-is
```sh
❯ pmdr q -b 5
Notification (id: 67) created and queued
```

Let's add timestamp like this.
To-be
```sh
❯ pmdr q -b 5
[2023-01-22 14:12] Notification (id: 67) created and queued
```

**Comment by divaspathak** [comment]
I want to work on this issue, can you please assign it to me?
