### ISSUE TITLE
How to become a contributor ? 

### ISSUE THREAD

**Issue by docongminh** [24seconds/rust-cli-pomodoro#139]
Hi. I am new Rust developer. Now i want to improve my skill by contribute open-source project

**Comment by 24seconds** [comment]
How about starting with this issue? https://github.com/24seconds/rust-cli-pomodoro/issues/135 @docongminh

**Comment by docongminh** [comment]
@24seconds  Ok. I a bit material research overview your project and start contribute on weekend

**Comment by 24seconds** [comment]
> @24seconds Ok. I need a bit material research overview your project and start contribute on weekend

Read the README.md (poor though..) and Read the code and leave some questions if you have.

**Comment by docongminh** [comment]
@24seconds  oke. Thanks
