### ISSUE TITLE
Feature: arrow up key shows previous command

### ISSUE THREAD

**Issue by 24seconds** [24seconds/rust-cli-pomodoro#142]
## Description
Usually terminal supports thie feature: when I entered `arrow up key`, then the terminal automatically shows previous command.

Maybe it would be nice to implement this feature in pomodoro cli

**Comment by TheRustyPickle** [comment]
I believe this can be added with [rustyline](https://github.com/kkawakam/rustyline). If it's alright I would like to work on this.

**Comment by 24seconds** [comment]
Hello, @TheRustyPickle , thank you for the comment. Yes you can. Before we dive in, it's good to clarify what the issue is.
As you already know, when we run the `rust-cli-pomodoro` then it shows like this.

<img width="1053" alt="image" src="https://user-images.githubusercontent.com/34280965/223586232-247c0203-f752-4625-ba96-b53c92d7f9db.png">
In this case, I had to type the command manually. (No auto complete, no history supported). I want to solve this problem - command typing inconvenience.

Yes, I also think `rustyline` can solve this problem. And I think `gluesql` is a good example of using `rustyline` maybe.
Maybe you can take a look these two files? (I didn't read the code but might helpful haha)
- https://github.com/gluesql/gluesql/blob/e32984c96a71bdc09f4e6fa76a7479c9c5af4060/cli/src/cli.rs#L1
- https://github.com/gluesql/gluesql/blob/e32984c96a71bdc09f4e6fa76a7479c9c5af4060/cli/src/helper.rs#L1

Good luck!
