### ISSUE TITLE
Dependency upgrade: clap version (3.2.22 -> 4.1.10)

### ISSUE THREAD

**Issue by 24seconds** [24seconds/rust-cli-pomodoro#152]
## Description
Currently `clap` version is low. It's good to upgrade it to latest one.

**Comment by TheRustyPickle** [comment]
@24seconds, I can help upgrade the `clap` version.

**Comment by 24seconds** [comment]
Helll @TheRustyPickle . Oh thank you! 😆🙇‍♂️
