### ISSUE TITLE
Why is main.rs using the tokyo::sync::oneshot channels?

### ISSUE THREAD

**Issue by Pablito2020** [24seconds/rust-cli-pomodoro#16]
Hi!
First of all, emphasize that I have seen the project and it fits exactly in my needs (to have an offline tool to manage pomodoro times), and I want to contribute to the project.

I've been looking at the code for a while and I can't understand why are you using _oneshot::channel_ for communicating between the different threads. Couldn't the first tokio::spawn thread delegate the function to display the type of error/action to the thread that analyzes the user input? With this form we wouldn't need the tokyo::sync::oneshot channel, (element that has made my reading of the code a little bit more difficult).

![channel figure](https://user-images.githubusercontent.com/18640261/145090672-d5b3b50b-d5ad-47a6-9f59-acce78f3f49e.png)

Finally, why is this project using the tokio library instead of the standard thread api from rust? From what I have seen I would say that all the added functionalities can be done (without much more complication) with the standard library. Emphasize that in case you say that the tokio library is not really necessary, I could contribute to port the current code to a new one that uses the standard thread library.

Thanks in advance and that said, I will try to contribute when I can, although it has to be said that I am relatively new to rust 😅

**Comment by 24seconds** [comment]
Hello and thank you for being interested in this project!

As I understand, there are two things in this issue

1. The reason of using oneshot
2. The reason of using tokio

#### The reason of using oneshot
This app behaves like this
1. waiting user input
2. user make input (ex: `create -w 25 -b 5`)
3. pomodoro handles input
4. pomodoro makes output (ex: `Notification (id: 8) created`)
5. waiting user input... and so on.

This is an image of real usage.
![image](https://user-images.githubusercontent.com/34280965/145148164-34f360fb-f178-4ece-ab53-90c142feeaab.png)

I noticed that step 1, 2, 3, 4 should be sequential, not concurrent. If the step is concurrent, the terminal would be really messy. For example, say we can wait user input while pomodoro handles input. But if we do like that, terminal output would be mixed with user's input message and pomodoro's output message.

#### The reason of using tokio
Just for fun, nothing special. I like to learn something by making toy project. This case, tokio is the target to learn. If you like to port, then I can learn standard thread library.. so seems good to me.

**Comment by Pablito2020** [comment]
Yeah, I get it. So, if the first thread has to wait until the other thread has finished, wouldn't it be better to do it in a sequential way? 
I mean, if the application is working like this:

Thread 2 ->Read Input (blocking) and send it to main thread
(here thread 2 will block until main thread has finished the task, only main thread is "working")
Main thread -> Parse Input
Main thread -> Make action with input and send result to thread 2
(here main thread will be blocked until thread 2 sends a new input, only thread 2 is "working" )
Thread 2 -> Show result of main and block for user input

Wouldn't it be better to do everything sequential? Minimizing the cost of creating threads and synchronize them? I mean, if you would like to learn the tokio library for this project, concurrency is 100% needed on the #13 issue (because the solution could be to create a daemon thread that waits N seconds (time between current time and the final notification) and then add the same notification after that time has expired).

**Comment by 24seconds** [comment]
Thank you for the opinion.   

### About sequential
If the application makes everything sequential, then it can not handle notification. If I think wrong, please correct me!
Let me give you an example, say we created a notification and this notification will alert 25 minutes after from now and alert again 30 minutes after from now (work time alert and break time alert for each).

While we are waiting user input or handling user input, `notification should work on time`. Therefore, asynchronous things should be done for this.

So as you said, if we block main thread and thread2 is waiting for the user input, I don't know how to handle notification. 

### using or creating thread
About using or creating thread, I think it's okay. As tokio document said, creating the task is not a huge thing.
> Tasks in Tokio are very lightweight. Under the hood, they require only a single allocation and 64 bytes of memory. Applications should feel free to spawn thousands, if not millions of tasks.
[tokio spawning document](https://tokio.rs/tokio/tutorial/spawning)

**Comment by Pablito2020** [comment]
Yeah, I am not saying to do all the application sequential (since as you've said, this is impossible if we want to have notifications and more advanced features).
My point is that we don't need to create two threads (one for parsing the user input and other for making an action). For example, create the following scenario:
    1) User creates a notifcation.
    2) User deletes all the notifications.

If we delegate the function of creating the notification thread to the main thread, the diagram would look like this:

![notification](https://user-images.githubusercontent.com/18640261/145408817-bad28dbb-e56a-42f1-bed9-be74a0593291.png)

The same steps for the current implementation, would look something like this:

![current-main](https://user-images.githubusercontent.com/18640261/145418551-7ad14158-ce70-406f-a231-66623aae7f5e.png)

As you can see, the first diagram is easier to read/analyze than the first, and they do the same work.

As I said previously, if you think that we can do this refactor on the project, I can offer to do the work for the pull request.

Cheers!

**Comment by 24seconds** [comment]
Thank you for the detailed explanation with nice diagrams!   
Yes, now I get it. Right. Maybe this app doesn't need oneshot. If you can work on this, feel free to do so!

**Comment by Pablito2020** [comment]
I finally did a pull-request implementing main.rs without oneshot (#17). As I said on the comment of the request, I started to clean a little bit of code making smaller functions because, if we keep the functions long and specific and the project get's "big", it can lead to a mess.

A nice issue to work right now before implementing new features would be to think/refactor the project in different modules, and have a nice and robust structure that is scalable and maintainable.  For example, thinking about how the project can achieve 
the "multiple notifications feature" before implementing it, and how can decouple the BBDD related thinks from main.rs, decoupling the argument-parser library from main, etc, etc.

**Comment by 24seconds** [comment]
Thank you for the contribution. I agree with you about making smaller functions or some refactor and separating in different modules.

But I think refactoring and implementing new features can be done concurrently. If we want to implement new features eagerly, then we can do it while we are refactoring.

Because this project is too small for now, everything can possible :D

**Comment by Pablito2020** [comment]
This issue is fixed on #17. Clossing the issue 😄.
