### ISSUE TITLE
Feature: command auto complete

### ISSUE THREAD

**Issue by 24seconds** [24seconds/rust-cli-pomodoro#63]
### Description
When I use the git command, git supports auto complete. For example, I typed `git sta` and pressed `tab` then git showed suggestions. I can select one of suggestions with arrow keys (up/down) and tab and enter.  

<img width="522" alt="image" src="https://user-images.githubusercontent.com/34280965/168519710-afcfa4f8-3f84-48e5-a122-e0a29861e1c5.png">
Fig 1. `git sta` example

It would be nice for pomodoro to support this feature also

**Comment by 24seconds** [comment]
To-be
```
> pomodoro cre
# After pressing the tab, then the terminal should show like this
> pomodoro create
```

**Comment by 24seconds** [comment]
Maybe using this can solve this issue?
- https://github.com/clap-rs/clap/tree/master/clap_complete#about
- related blog: https://kbknapp.dev/shell-completions/

**Comment by 24seconds** [comment]
Hello, @TheRustyPickle. I'm sorry that I'm so busy (😢) that I have not researched about this issue.
So correct me if I'm wrong.  
As I commented above, I found clap supports `clap_complete`. Could you take a look and see if it solves this issue?

**Comment by TheRustyPickle** [comment]
Yes, will look into it. Thanks for the helpful links.
